# Server
server.port=8080
spring.application.name=roomrental-api
spring.profiles.default=local

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.expiration=900000

# Frontend URL cho CORS
frontend.url=http://localhost:5173
app.cookie.secure=false

# Upload file size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=80MB

#Backup configuration
backup.directory=backups
backup.enabled=true
backup.retention-count=7
backup.cron=0 0 2 * * *

# Post expiration configuration
post.expiration.cron=0 55 1 * * *
